[package]
name = "rust-python"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22.5", features = ["auto-initialize"] }

[build-dependencies]
cc = "1.1.31"

[lib]
crate-type = ["cdylib", "rlib"]
