name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint rust-c
      run: cargo fmt
      working-directory: ./rust-c

    - name: Build  rust-c
      run: cargo build
      working-directory: ./rust-c
      
    - name: Run tests rust-c
      run: cargo test
      working-directory: ./rust-c
